services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sortir}
      MYSQL_USER: ${MYSQL_USER:-sortir_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sortir_password}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}" ]
      timeout: 5s
      retries: 10
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  # Application Symfony
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - DATABASE_URL=mysql://${MYSQL_USER:-sortir_user}:${MYSQL_PASSWORD:-sortir_password}@database:3306/${MYSQL_DATABASE:-sortir}?serverVersion=8.0
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
        # Supprimer la configuration fixtures si elle existe
        rm -f config/packages/doctrine_fixtures.yaml &&
        composer install --no-dev --optimize-autoloader &&
        php bin/console doctrine:database:create --if-not-exists &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console cache:clear --env=prod &&
        php -S 0.0.0.0:8000 -t public
      "

volumes:
  database_data:
